.\" Process this file with
.\" groff -man -Tascii microcom.1
.\"
.TH MICROCOM 1 "SEPTEMBER 2002" Linux "User Manuals"
.SH NAME
microcom \- Simple serial port terminal program
.SH SYNOPSIS
.B microcom
.BI [ options ]
.BI < device >
.BI [ cmd ]
.B ...
.SH DESCRIPTION
.B microcom
is a simple serial port connection tool. It does not implement
terminal emulation or special modem support, but is very efficiant
when you need a serial connection to a device connected to the serial
port. It can either be run interactively, or it can run an program
with the standard input and output of that program connected to the
serial port.
.LP
The program will run until it is terminated by the user by
SIGINT. This is normally done by pressing control-C.
.SH OPTIONS
.IP "-b \fIbaud\fR, --baud=\fIbaud"
Set the baud rate. The default is 115200 baud.
.IP "-F, --no-flow"
Disable hardware (CTS/RTS) flow control.
.IP "-h, --help"
Show help.
.IP "-p \fIus\fR, --pause=\fIus"
Pause for
.I us
microseconds between all characters sent to the serial port.
.SH EXAMPLES
To connect to /dev/ttyS0 at 115200 baud with hardware flow control:
.IP
microcom /dev/ttyS0
.LP
To connect to /dev/ttyS0 at 9600 baud with no flow control:
.IP
microcom -b 9600 -F /dev/ttyS0
.LP
To send the file foo.bar on the serial port at 38400 baud:
.IP
microcom -b 38400 -F /dev/ttyS0 cat foo.bar
.LP
This works since the standard output of the
.I cat
command is connected to the serial port. The standard input of the
command is also connected, but it is not used in this example.
.SH DIAGNOSTICS
All commands will hopefully generate meaningful error messages on all
possible errors.
.SH BUGS
To be discovered...
.SH AUTHOR
Tobias Ringstrom <tobias@ringstrom.mine.nu>
.SH "SEE ALSO"
.BR minicom (1)
